DIRECTORY:
  dataset: ../Dataset/Train/
LOGGER:
  debug: false
  plot:
  - loss
  - elapsed_time
  - acc
  wandb: True
  logging_interval: 100
TRAINER:
  seed: 1010
  model: b0 #vit
  optimizer: adam
  learning_rate: 0.0001
  weight_decay: 0.1
  loss: CrossEntropyLoss
  metric:
  - accuracy
  n_epochs: 100
  amp: false
  early_stopping_target: val_loss
  early_stopping_patience: 5
  early_stopping_mode: max

DATASET:
  val_size: 0.1
  img_size: 224
  mode: ori #ela # ori # ela
DATALOADER:
  batch_size: 10
  num_workers: 0
  shuffle: true
  pin_memory: true
  drop_last: false
METRICS:
  mode : notarc
  easy_margin : False
